/**
 * Stills collections for the OS shell.
 * Image lists reuse the existing site page order / folders.
 */
export const STILLS = [
  {
    slug: "people",
    title: "People",
    description: "Portrait and everyday life photography",
    date: null,
    images: [
        "/life/life-87.jpg",
        "/life/life-74.jpg",
        "/life/life-81.png",
        "/life/life-86.jpg",
        "/life/life-77.png",
        "/life/life-78.png",
        "/life/life-80.png",
        "/life/life-75.jpg",
        "/life/life-83.png",
        "/life/life-76.jpg",
        "/life/life-35.png",
        "/life/life-68.jpg",
        "/life/life-82.png",
        "/life/life-38.png",
        "/life/life-79.png",
        "/life/life-67.png",
        "/life/life-85.jpg",
        "/life/life-72.png",
        "/life/life-40.png",
        "/life/life-53.png",
        "/life/life-30.png",
        "/life/life-69.jpg",
        "/life/life-61.jpg",
        "/life/life-56.png",
        "/life/life-66.png",
        "/life/life-50.png",
        "/life/life-33.png",
        "/life/life-84.png",
        "/life/life-70.jpg",
        "/life/life-45.png",
        "/life/life-60.jpg",
        "/life/life-55.png",
        "/life/life-1.jpg",
        "/life/life-58.png",
        "/life/life-37.jpg",
        "/life/life-62.jpg",
        "/life/life-63.jpg",
        "/life/life-54.png",
        "/life/life-12.png",
        "/life/life-64.jpg",
        "/life/life-59.png",
        "/life/life-46.png",
        "/life/life-47.png",
        "/life/life-36.png",
        "/life/life-34.png",
        "/life/life-51.png"
    ],
  },
  {
    slug: "outdoors",
    title: "Outdoors",
    description: "Landscapes, trails, and open air",
    date: null,
    images: [
        "/outdoors/outdoors-36.jpg",
        "/outdoors/outdoors-1.png",
        "/outdoors/outdoors-2.png",
        "/outdoors/outdoors-26.png",
        "/outdoors/outdoors-17.png",
        "/outdoors/outdoors-42.png",
        "/outdoors/outdoors-19.png",
        "/outdoors/outdoors-5.png",
        "/outdoors/outdoors-38.png",
        "/outdoors/outdoors-39.png",
        "/outdoors/outdoors-40.png",
        "/outdoors/outdoors-41.png",
        "/outdoors/outdoors-33.jpg",
        "/outdoors/outdoors-35.jpg",
        "/outdoors/outdoors-18.png",
        "/outdoors/outdoors-37.png",
        "/outdoors/outdoors-6.png",
        "/outdoors/outdoors-27.png",
        "/outdoors/outdoors-28.png",
        "/outdoors/outdoors-4.png",
        "/outdoors/outdoors-30.png",
        "/outdoors/outdoors-12.png",
        "/outdoors/outdoors-25.png",
        "/outdoors/outdoors-15.png",
        "/outdoors/outdoors-44.png",
        "/outdoors/outdoors-24.png",
        "/outdoors/outdoors-31.png",
        "/outdoors/outdoors-32.jpg",
        "/outdoors/outdoors-29.png",
        "/outdoors/outdoors-34.jpg"
    ],
  },
  {
    slug: "garments",
    title: "Garments",
    description: "Fashion and garment photography",
    date: null,
    images: [
        "/garments/garments-63.png",
        "/garments/garments-62.png",
        "/garments/garments-4.jpg",
        "/garments/garments-60.jpg",
        "/garments/garments-61.jpg",
        "/garments/garments-22.jpg",
        "/garments/garments-26.png",
        "/garments/garments-5.png",
        "/garments/garments-45.png",
        "/garments/garments-27.gif",
        "/garments/garments-56.png",
        "/garments/garments-3.png",
        "/garments/garments-15.png",
        "/garments/garments-57.png",
        "/garments/garments-52.png",
        "/garments/garments-53.png",
        "/garments/garments-50.jpg",
        "/garments/garments-49.jpg",
        "/garments/garments-54.png",
        "/garments/garments-55.png",
        "/garments/garments-11.png",
        "/garments/garments-12.png",
        "/garments/garments-48.jpg",
        "/garments/garments-43.png",
        "/garments/garments-58.png",
        "/garments/garments-59.png",
        "/garments/garments-42.png",
        "/garments/garments-46.jpg",
        "/garments/garments-9.jpg",
        "/garments/garments-51.jpg",
        "/garments/garments-29.jpg",
        "/garments/garments-38.png",
        "/garments/garments-39.png",
        "/garments/garments-40.png",
        "/garments/garments-41.png",
        "/garments/garments-44.png"
    ],
  },
  {
    slug: "urban",
    title: "Urban",
    description: "City and urban photography",
    date: null,
    images: [
        "/urban/urban-33.png",
        "/urban/urban-4.png",
        "/urban/urban-5.png",
        "/urban/urban-10.png",
        "/urban/urban-6.png",
        "/urban/urban-9.png",
        "/urban/urban-35.png",
        "/urban/urban-34.png",
        "/urban/urban-3.png",
        "/urban/urban-7.png",
        "/urban/urban-8.png",
        "/urban/urban-11.png",
        "/urban/urban-12.png",
        "/urban/urban-37.png",
        "/urban/urban-13.png",
        "/urban/urban-14.png",
        "/urban/urban-15.png",
        "/urban/urban-38.png",
        "/urban/urban-17.png",
        "/urban/urban-19.png",
        "/urban/urban-20.png",
        "/urban/urban-21.png",
        "/urban/urban-23.png",
        "/urban/urban-24.png",
        "/urban/urban-25.png",
        "/urban/urban-26.png",
        "/urban/urban-27.png",
        "/urban/urban-29.png",
        "/urban/urban-30.png",
        "/urban/urban-31.png",
        "/urban/urban-32.png",
        "/urban/urban-36.png"
    ],
  },
];

export function getStill(slug) {
  return STILLS.find((item) => item.slug === slug) || null;
}
